# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: markymark13/jekyll-template-master
  branch: main
  identity_url: https://auth.decapbridge.com/sites/b3547417-ab29-4448-944c-9454c5b0ce86
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://jekyll-template-master.pages.dev



media_folder: "assets/images"
public_folder: "assets/images/"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    extension: "md"  # Add this!
    format: "frontmatter"  # Add this!
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "faq"
    label: "FAQ"
    files:
      - file: "_data/faq.json"
        label: "All FAQ"
        name: "faq"
        fields:
          - label: "FAQ"
            name: "faq"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}

  - name: "products"
    label: "Products"
    files:
      - file: "_data/products.json"
        label: "All Products"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Price", name: "price", widget: "number", value_type: "float"}
              - {label: "Photo", name: "photo", widget: "image", required: false}
              - {label: "Checkout URL", name: "checkout_url", widget: "string"}


  - name: "services"
    label: "Services"
    files:
      - file: "_data/services.json"
        label: "All Services"
        name: "services"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
              - {label: "Photo", name: "photo", widget: "image", required: false}
              - label: "Features"
                name: "features"
                widget: "list"
                field: {label: "Feature", name: "feature", widget: "string"}

  - name: "testimonials"
    label: "Testimonials"
    files:
      - file: "_data/testimonials.json"
        label: "All Testimonials"
        name: "testimonials"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Role", name: "role", widget: "string"}
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Photo", name: "photo", widget: "image", required: false}


  - name: "portfolio_images"
    label: "Portfolio Images"
    folder: "assets/images/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}          

  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Hero Header", name: "hero_header", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - label: "Section 1"
            name: "section1"
            widget: "object"
            required: false
            fields:
              - {label: "Header", name: "section1_header", widget: "string"}
              - {label: "Text", name: "section1_text", widget: "markdown"}
              - {label: "Image", name: "section1_image", widget: "image"}
          - label: "Section 2"
            name: "section2"
            widget: "object"
            required: false
            fields:
              - {label: "Header", name: "section2_header", widget: "string"}
              - {label: "Text", name: "section2_text", widget: "markdown"}
              - {label: "Image", name: "section2_image", widget: "image"}
              
      - file: "about.html"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Hero Header", name: "hero_header", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - label: "Section 1"
            name: "section1"
            widget: "object"
            fields:
              - {label: "Header", name: "section1_header", widget: "string"}
              - {label: "Text", name: "section1_text", widget: "markdown"}
              - {label: "Image", name: "section1_image", widget: "image"}